# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Tests CI
on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install 💾
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build & Publish Dry Run
        run: npm publish --dry-run
