# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Publish NPM @next
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install 💾
        run: npm ci

      - name: Version ⬆️
        run: npm version --new-version "v0.0.0-${FULL_SHA:0:6}" --no-git-tag-version
        env:
          FULL_SHA: ${{ github.sha }}

      - name: Publish @next 🚂
        run: npm publish --tag next --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
